export enum PATH {
  PROFILE = '/profile',
  REGISTER = '/register',
  NOT_FOUND = '/404',
  FORGOT_PASSWORD = '/forgot-password',
  NEW_PASSWORD = '/new-password',
  CARDS = '/cards',
  PACKS = '/packs',
  LOGIN = '/login',
  START = '/',
  TOKEN = ':token',
  ANY = '*',
  ID = ':id',
  USERS = '/users',
  CHAT = '/chat',
}
