export const ROUTES = {
  PROFILE: '/profile',
  REGISTRATION: '/registration',
  NOT_FOUND: '/404',
  FORGOT_PASSWORD: '/forgot-password',
  NEW_PASSWORD: '/new-password',
  CARDS: '/cards',
  PACKS: '/packs',
  LOGIN: '/login',
  START: '/',
  TOKEN: ':token',
  ANY: '*',
  ID: ':id',
  USERS: '/users',
  CHAT: '/chat',
} as const;
